### ISSUE TITLE
cannot connect to discord.com:443: undefined error: 0

### ISSUE THREAD

**Issue by allanp0e** [brainboxdotcc/templatebot#6]
hello , i just get this error when I run  templatebot, here is some more detailed message:

[2023-05-05 11:17:32] ERROR: HTTP(S) error on https connection to discord.com:443: Undefined error: 0
[2023-05-05 11:17:32] DEBUG: Cluster: 0 of 0 session starts remaining
libc++abi: terminating with uncaught exception of type dpp::connection_exception: Auto Shard: Cannot determine number of shards. Cluster startup aborted. Check your connection.
zsh: abort      ./templatebot

glad if you can help!

**Comment by braindigitalis** [comment]
what os is this? the zsh and c++abi don't seem usual for Linux or bsd?

looks like the system is forbidding the connection to discord.

**Comment by braindigitalis** [comment]
nvm the libc++abi is a clang thing
